language: ruby
rvm:
- 2.3.0
node_js:
- 6.2
install:
- "./bin/setup"
script:
- bundle exec jekyll build --trace
- bundle exec htmlproof ./_site --only-4xx
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "source" && "./bin/automated"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - USERNAME=gdad-s-river
  - EMAIL=arihantverma1994@gmail.com
