# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: gdad-s-river's blog
email: gdadsriver@gmail.com
description: gdad-s-river's tech ramblings on the web
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gdad-s-river.github.io" # the base hostname & protocol for your site
twitter_username: gdad_s_river
github_username:  gdad-s-river

# Build settings
markdown: kramdown

sass: 
  sass_dir: _sass
  style: compressed

google_analytics: UA-78165810-1
