# The blog configuration 

name: gdad-s-river's blog
description: gdad-s-river's blog
author: Arihant
permalink: /blog/:title/
timezone: Asia/Kolkata
email: arihantverma1994@gmail.com
twitter: gdad_s_river

# This is the default that's used to preview.
# Change this to your website's URL when you publish your site.
url: http://localhost:4000