name: gdad-s-river's blog
title: < gdad-s-river's blog />
markdown: redcarpet
exclude:
  - README.markdown
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - .ruby-version
  - .ruby-gemset
  - .gitignore
  - .travis.yml
  - bin/*
gems:
  - jekyll-assets
  - jekyll-feed
timezone: Asia/Kolkata

feed:
  path: atom.xml

author:
  twitter: gdad_s_river

assets:
  css_compressor: sass
  js_compressor: uglifier
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images

links:
  - title: About
    url: /about
  - title: Github
    url: https://github.com/gdad-s-river
    external: true
  - title: Twitter
    url: https://twitter.com/gdad_s_river
    external: true
  - title: Stackoverflow
    url: http://stackoverflow.com/users/5106072/gdad-s-river
    external: true
