source 'https://rubygems.org'

gem 'coffee-script'
gem 'font-awesome-sass'
gem 'sass'
gem 'uglifier'
gem 'guard'
gem 'html-proofer'
gem 'guard-livereload', '~> 2.3.0'
gem 'jekyll'
gem 'jekyll-assets'
gem 'jekyll-feed'
gem 'redcarpet'
